environment:
  matrix:
    - TARGET: vs2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: '"Visual Studio 15 2017"'
      # https://www.appveyor.com/docs/windows-images-software/#qt
      QTDIR: C:\Qt\5.12.6\msvc2017

    - TARGET: vs2019
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: '"Visual Studio 16 2019"'
      QTDIR: C:\Qt\5.12.8\msvc2017_64

#branches:
#  except:
#    - more_travis_builds

install:
  - set PATH=%PATH%;%QTDIR%\bin

before_build:
- cmd: cmake -DCMAKE_PREFIX_PATH=%QTDIR%\lib\cmake\Qt5 -G %GENERATOR% .

build_script:
- cmd: cmake --build .

test_script:
- cmd: ctest --verbose --parallel 4 -C Debug
